title: 'Gabe Peters | Philantropist, Sports Fanatic, Guy with a Beard'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3409485148731619
  lightness: 0.5826400390360504
  brandStrength: 0.2164339
  brandColors:
    - '#202E31'
    - '#BDACA3'
    - '#424A66'
    - '#86819B'
    - '#E08865'
  rhythmicContrast: 0.2026102486997843
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-72104801-3
  facebook: null
favicon: null
name: gabepeters
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.03207339788787067
layout_spectrum: 1
